### ISSUE TITLE
RFE: support creation of product versions

### ISSUE THREAD

**Issue by pbabinca** [red-hat-storage/errata-tool#154]
Currently product versions cannot be created within the library nor with CLI.

**Comment by pbabinca** [comment]
I guess this could be based on list product versions that isn't merged yet: https://github.com/red-hat-storage/errata-tool/commit/7c7bf1f7af37dacaf427a18a83937884a2e614ed

**Comment by ktdreyer** [comment]
This seems like a good fit for https://github.com/ktdreyer/errata-tool-ansible.

I'm still trying to figure out what works best in python-errata-tool and what works best in errata-tool-ansible. So far there is almost no overlap.

**Comment by ktdreyer** [comment]
We're using errata-tool-ansible for more products now, and it's working well. errata-tool-ansible also has a good integration test suite that runs against a full dev ET server instance.

I prefer to not write any more code in python-errata-tool to manage product configurations with Python or the `errata-tool` CLI, because Ansible is a better fit for that type of configuration management. Are you ok with that?

**Comment by pbabinca** [comment]
Sounds good to me
